export const ORDER_ERROR = {
  INVALID_PRODUCTS: "INVALID_PRODUCTS",
  DUPLICATE_PRODUCTS: "DUPLICATE_PRODUCTS",
  MINIMUM_ORDER_VALUE: "MINIMUM_ORDER_VALUE",
  INSUFFICIENT_STOCK: "INSUFFICIENT_STOCK",
  ORDER_NOT_FOUND: "ORDER_NOT_FOUND",
  INVALID_STATUS_TRANSITION: "INVALID_STATUS_TRANSITION",
} as const;
