/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/bootstrap`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../shared/components/ui/empty-state`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/cart` | `/cart`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/order-success` | `/order-success`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/browse` | `/browse`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/checkout/payment` | `/checkout/payment`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/join/confirmation` | `/join/confirmation`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/join/scan-distributor-qr` | `/join/scan-distributor-qr`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/orders` | `/orders`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/welcome` | `/welcome`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/orders/[id]` | `/orders/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/bootstrap`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/../shared/components/ui/empty-state`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/cart` | `/cart`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/order-success` | `/order-success`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/browse` | `/browse`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/checkout/payment` | `/checkout/payment`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/join/confirmation` | `/join/confirmation`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/join/scan-distributor-qr` | `/join/scan-distributor-qr`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/orders` | `/orders`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/welcome` | `/welcome`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/orders/[id]` | `/orders/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/bootstrap${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/../shared/components/ui/empty-state${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/cart${`?${string}` | `#${string}` | ''}` | `/cart${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/order-success${`?${string}` | `#${string}` | ''}` | `/order-success${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/browse${`?${string}` | `#${string}` | ''}` | `/browse${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/checkout/payment${`?${string}` | `#${string}` | ''}` | `/checkout/payment${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/join/confirmation${`?${string}` | `#${string}` | ''}` | `/join/confirmation${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/join/scan-distributor-qr${`?${string}` | `#${string}` | ''}` | `/join/scan-distributor-qr${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/orders${`?${string}` | `#${string}` | ''}` | `/orders${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/welcome${`?${string}` | `#${string}` | ''}` | `/welcome${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/bootstrap`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../shared/components/ui/empty-state`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/cart` | `/cart`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/order-success` | `/order-success`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/browse` | `/browse`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/checkout/payment` | `/checkout/payment`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/join/confirmation` | `/join/confirmation`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/join/scan-distributor-qr` | `/join/scan-distributor-qr`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/orders` | `/orders`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/welcome` | `/welcome`; params?: Router.UnknownInputParams; } | `${'/(app)'}/orders/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/orders/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `${'/(app)'}/orders/[id]` | `/orders/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
